name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
	  - dev-v1.0.2

jobs:
  deploy:
    runs-on: ubuntu-latest
	steps:
	  - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
	    with:
		  github_token: ${{ secrets.GITHUB_TOKEN }}